### ISSUE TITLE
Skin directory not found in /Resources!

### ISSUE THREAD

**Issue by NicolasParaskevas** [DannyGlover/Solar2DTux#23]
I installed solar2dTux in a linux mint virtual machine, when I launched the application it only opened the solar2d console and had this error: "Skin directory not found in /Resources!"

**Comment by DanS2D** [comment]
Hello @NicolasParaskevas.

- How did you install Solar2DTux? 
- What version of linux mint?

**Comment by NicolasParaskevas** [comment]
Hello @DannyGlover
I have linux mint 20 and I installed solar2dTux by running the bash script install.sh using the bash command. I didn't extract the compressed file, I just ran the script.

**Comment by DanS2D** [comment]
@NicolasParaskevas 

> Hello @DannyGlover
> I have linux mint 20 and I installed solar2dTux by running the bash script install.sh using the bash command. I didn't extract the compressed file, I just ran the script.

Ah, that's where you went wrong.

Extract the entire archive first, then `cd` into the extracted folder, then run `./install.sh`

**Comment by NicolasParaskevas** [comment]
@DannyGlover I tried what you said and it works just fine now. Thanks!
