### ISSUE TITLE
How to install/run?

### ISSUE THREAD

**Issue by onlinesid** [DannyGlover/Solar2DTux#3]
I downloaded the zip, unzip it, but then how to install/run?

**Comment by DanS2D** [comment]
Hello @onlinesid.

We aren't quite at a release ready stage yet. We are trying hard to get everything ready for a first release really soon.

When that happens, there'll be a deb installer you can use to run the simulator as you would on windows or mac.

Of course, it is possible to build/run from the source, but there are a lot of moving parts at the moment... So explaining the process to do that would be a fruitless endeavour at the current time.

Thanks for your interest. I'll keep this open so I can notify you when the release happens.

**Comment by onlinesid** [comment]
Thanks @DannyGlover I really like what I've seen so far so support for Linux is fantastic!

**Comment by boogiefromzk** [comment]
Also interested.

**Comment by rcraig12** [comment]
Hello @boogiefromzk  as @DannyGlover  has said. We are not quite at release stage yet! Hang in there because it is close and we hope to be getting people to give it a whirl really soon :)

**Comment by DanS2D** [comment]
@onlinesid @boogiefromzk 

I've just shared the pre release of version 1.0.0 on the forums. See here for more details: https://forums.solar2d.com/t/solar2dtux-pre-release-build-testing-get-it-here-solar2d-simulator-on-linux/352200

Let me know how it goes!
Thank you
